image: docker:24.0.5
services:
  - docker:24.0.5-dind

stages:
  - build_image
  - deploy_prod

# 构建 seed-user 服务的 Docker 镜像
build_image_user:
  stage: build_image
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - pwd
    - cd ./user
    - docker build -t moesamazzt/seed-user:$CI_COMMIT_REF_SLUG .
    - docker push "$CI_REGISTRY_IMAGE":"$CI_COMMIT_REF_SLUG"
    - echo "Deployed Image seed-user Service!!"
  only:
    - main

# 部署 user 服务到服务器
deploy_prod_user:
  stage: deploy_prod
  before_script:
    - docker login -u "$CI_REGISTRY_USER" -p "$CI_REGISTRY_PASSWORD"
  script:
    - cd user
#    - docker push myregistry/user:test
    - echo "Deployed Environment seed-user Service!!"
  only:
    - main
#  environment:
#    name: test
#    url: https://test.example.com
