// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package handler

import (
	"net/http"

	sse "chat/api/internal/handler/sse"
	"chat/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/send",
				Handler: sse.SendHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/subscribe/:userId",
				Handler: sse.SubscribeHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/chat/sse"),
	)
}
