// Code generated by goctl. DO NOT EDIT.
package types

type UserLoginRequest struct {
	UserNumber   string `json:"userNumber"`
	UserPassword string `json:"userPassword"`
}

type UserRegisterRequest struct {
	UserName     string `json:"userName"`
	UserPassword string `json:"userPassword"`
}

type UserLoginResponse struct {
	Token string `json:"token"`
}

type UserRegisterResponse struct {
	UserNumber string `json:"userNumber"`
}
