// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	product "product/internal/handler/product"
	"product/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodGet,
				Path:    "/product/get",
				Handler: product.ProductGetHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/product/list",
				Handler: product.ProductListHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/product/create",
				Handler: product.ProductCreateHandler(serverCtx),
			},
		},
		rest.WithPrefix("/api/v1"),
	)
}
