// Code generated by goctl. DO NOT EDIT.
// goctl 1.7.3

package types

type SendReq struct {
	UserId   string `json:"userId"`   // 用户ID，消息发送者
	TargetId string `json:"targetId"` // 目标用户或群组ID
	Message  string `json:"message"`  // 消息内容
}

type SendResp struct {
	Status  string // 消息发送状态，如 "success" 或 "failed"
	Message string // 附加信息
}

type SubscribeReq struct {
	UserId string `path:"userId"` // 用户ID，标识订阅者
}

type SubscribeResp struct {
	Status  string // 订阅状态，如 "success" 或 "failed"
	Message string // 附加信息
}
